import type { Locale } from '@/lib/locales';

export const localeLabel: Record<Locale, string> = {
  ja: '日本語',
  en: 'English',
  zh: '中文',
};

const ja = {
  defaultTitle: 'daaquan | つくる、試す、書き残す。',
  siteDescription: '作品と、日々の活動と、角度をつけて話す会議室。daaquan の個人サイト。',
  skip: '本文へ移動',
  homeAria: 'daaquan ホーム',
  intro: 'つくる、試す、書き残す。',
  navLabel: 'メインナビゲーション',
  home: 'ホーム',
  work: 'つくったもの',
  notes: 'ノート',
  now: 'いま',
  nowShort: '進行中',
  progressTitle: 'WORK IN PROGRESS',
  progress: '小さくつくって、少しずつ育てる。',
  room: '会議室',
  languages: '言語',
  rss: 'RSS',
  sample: 'サンプル',
  pinned: '固定',
  replies: '返信',
  noReplies: 'まだ返信がない',
  lastReply: (name: string, move: string) => `最後は${name}の${move}`,
  topics: (count: number) => `${count} 話題`,
  replyStat: (count: number) => `${count} 返信`,
  people: (count: number) => `${count} 人`,
  allTags: 'すべて',
  tagsLabel: '話題のタグ',
  residentsLabel: '会議室の住人',
  boardEyebrow: 'NOTES / 会議室',
  boardTitleLead: '机の上の、',
  boardTitle: '会議室。',
  boardIntro: '専門の住人が、読んだものに角度をつけて話す。要約、転用、自前、横から。名前のない感想は置かない。',
  notesTitle: '会議室',
  notesDescription: '専門の住人が、読んだものに角度をつけて話すノート。要約、転用、自前、横から。',
  tagTitle: (label: string) => `${label} の話題`,
  backToNotes: '← 会議室',
  otherNotes: '← ほかの話題',
  angles: 'ついた角度',
  feedLink: 'RSS で更新を読む',
  missingTitle: 'ページが見つかりません。',
  missingBody: 'URL を確認するか、ホームから作品やノートを探してみてください。',
  missingHome: 'ホームへ戻る',
  shortcuts: 'コンテンツのショートカット',
  heroLead: 'アイデアを、',
  heroEmphasis: '小さく動くものに。',
  heroBody: 'つくったもの、いま取り組んでいること。',
  heroBody2: '技術と AI を触りながら、日々の発見をここに集めます。',
  seeWork: 'つくったものを見る',
  openNotes: '会議室を開く',
  sampleNotice: 'はじめの一歩。作品と、最初の三話題はサンプルです。会議室のルールは、この場所の本番です。',
  workCard: 'つくったもの・展示サンプル',
  notesCard: '角度をつけて話す',
  nowCard: 'いま、気になっていること',
  elsewhereCard: 'コードと試行錯誤',
  workIntro: '便利なもの。気になるもの。まずは、つくってみる。',
  sampleBadge: '展示サンプル',
  seeTopics: '話題を見る',
  notesIntro: '住人が、読んだものに角度をつけて話す。',
  nowTitle: 'いま、気になっていること。',
  nowBody: '完成する前の、考えごとも置いておく。',
  nowBody2: 'そのときの活動や関心を、ここに残していきます。',
  nowBadge: '掲載テーマのサンプル',
  nowItems: [
    ['AI を日常の道具にする', '技術の変化を、実際の使い道につなげる。'],
    ['小さなプロダクトを育てる', '自分が使いたいものを、動くかたちに。'],
    ['学びを、外にひらく', '発見も失敗も、次の誰かのヒントに。'],
  ],
  helloTitle: 'ここから、つながる。',
  helloBody: '作品のコードや、これからの試行錯誤は GitHub に。',
  helloBody2: 'この場所も、つくりながら育てていきます。',
  seeGithub: 'GitHub を見る',
  copy: 'コードをコピー',
  copied: 'コピーしました',
  copyFailed: 'コピーできませんでした。コードを選択してコピーしてください。',
  projects: {
    automation: {
      title: 'AI とつくる、小さな仕組み',
      description: '繰り返す作業を少し楽に。AI ワークフローやツールの実験を展示する場所。',
      linkLabel: '実験ノートを読む',
    },
    everyday: {
      title: '暮らしのための道具',
      description: 'タスクやメモを、もっと自然に。日常の小さな不便から生まれるもの。',
      linkLabel: 'いまのテーマを見る',
    },
  },
  moves: {
    summary: { label: '要約', detail: '読んだものを短く置く' },
    repurpose: { label: '転用', detail: '別の仕事の道具にする' },
    original: { label: '自前', detail: '自分の題で話す' },
    aside: { label: '横から', detail: '隣の話題に別の側から入る' },
  },
  voices: {
    desk: { name: '机', field: '拠点', line: '話の入口を置く。' },
    trend: { name: '潮流', field: '注視', line: '読んだあとで、短く置く。' },
    adapt: { name: '転用', field: '読み替え', line: '他人の話を、別の道具にする。' },
    own: { name: '自前', field: '着想', line: '借り物で終わらせず、題を立てる。' },
    aside: { name: '横槍', field: '角度', line: '隣の話題に、別の側から入る。' },
  },
  tags: {
    ai: { label: 'AI', blurb: '新しい機能を、一つの作業に落として話す。' },
    build: { label: '開発', blurb: '小さくつくって、直した記録を残す。' },
    days: { label: '日々', blurb: 'このサイトを、興味の近い人の拠点にする。' },
    room: { label: '会議室', blurb: '動きを名乗ってから書く。それがこの板のルールだ。' },
    tools: { label: '道具', blurb: '手で触った道具と、その手触り。' },
    trend: { label: '潮流', blurb: '見出しだけでは話題にしない。読んでから置く。' },
  },
  unknownTag: (slug: string) => `${slug} の話題。`,
};

const en: typeof ja = {
  defaultTitle: 'daaquan | make, try, write it down.',
  siteDescription: 'Work, daily notes, and a room where each reply names its angle. A personal site.',
  skip: 'Skip to content',
  homeAria: 'daaquan home',
  intro: 'Make, try, write it down.',
  navLabel: 'Main',
  home: 'Home',
  work: 'Work',
  notes: 'Notes',
  now: 'Now',
  nowShort: 'Now',
  progressTitle: 'WORK IN PROGRESS',
  progress: 'Build small, and keep going.',
  room: 'Room',
  languages: 'Language',
  rss: 'RSS',
  sample: 'Sample',
  pinned: 'Pinned',
  replies: 'Replies',
  noReplies: 'No replies yet',
  lastReply: (name, move) => `Last: ${name}, ${move}`,
  topics: count => `${count} topics`,
  replyStat: count => `${count} replies`,
  people: count => `${count} voices`,
  allTags: 'All',
  tagsLabel: 'Topic tags',
  residentsLabel: 'Voices in the room',
  boardEyebrow: 'NOTES / ROOM',
  boardTitleLead: 'On the desk,',
  boardTitle: 'a room.',
  boardIntro: 'Each voice reads, then speaks from a named angle: summary, remix, original, aside. A comment with no angle does not land here.',
  notesTitle: 'Room',
  notesDescription: 'Notes where each reply names its angle: summary, remix, original, or aside.',
  tagTitle: label => `${label} topics`,
  backToNotes: '← Room',
  otherNotes: '← Other topics',
  angles: 'Angles',
  feedLink: 'Read updates in RSS',
  missingTitle: 'Page not found.',
  missingBody: 'Check the URL, or go home and look through the work and notes.',
  missingHome: 'Back home',
  shortcuts: 'Shortcuts',
  heroLead: 'Turn an idea',
  heroEmphasis: 'into something small that runs.',
  heroBody: 'Things made, and things in progress.',
  heroBody2: 'Notes from trying tools, code, and AI.',
  seeWork: 'See the work',
  openNotes: 'Open the room',
  sampleNotice: 'A first step. The work and the first three topics are samples. The rules of the room are the real thing.',
  workCard: 'Work on display',
  notesCard: 'Talk from an angle',
  nowCard: 'What is on my mind',
  elsewhereCard: 'Code and attempts',
  workIntro: 'Useful things. Curious things. Make one first.',
  sampleBadge: 'Sample',
  seeTopics: 'See topics',
  notesIntro: 'The voices speak from an angle.',
  nowTitle: 'What is on my mind.',
  nowBody: 'Unfinished thoughts can sit here too.',
  nowBody2: 'This is where current work and interests stay.',
  nowBadge: 'Sample themes',
  nowItems: [
    ['Make AI a daily tool', 'Connect a technical change to one real use.'],
    ['Grow a small product', 'Turn something I want into something that runs.'],
    ['Leave the learning open', 'A find, or a failure, might help the next person.'],
  ],
  helloTitle: 'Start here.',
  helloBody: 'Code and the next attempts live on GitHub.',
  helloBody2: 'This place grows while it is being made.',
  seeGithub: 'See GitHub',
  copy: 'Copy code',
  copied: 'Copied',
  copyFailed: 'Could not copy. Select the code and copy it yourself.',
  projects: {
    automation: {
      title: 'Small systems, built with AI',
      description: 'A place for experiments that make a repeated task a little easier.',
      linkLabel: 'Read the experiment note',
    },
    everyday: {
      title: 'Tools for daily life',
      description: 'Tasks and notes, a bit more natural. Built from small everyday friction.',
      linkLabel: 'See current themes',
    },
  },
  moves: {
    summary: { label: 'Summary', detail: 'Put the reading in short' },
    repurpose: { label: 'Remix', detail: 'Turn it into a tool for other work' },
    original: { label: 'Original', detail: 'Speak from your own title' },
    aside: { label: 'Aside', detail: 'Enter the next topic from another side' },
  },
  voices: {
    desk: { name: 'Desk', field: 'Home base', line: 'Sets the way in.' },
    trend: { name: 'Tide', field: 'Watch', line: 'Reads first, then leaves a short note.' },
    adapt: { name: 'Remix', field: 'Reframe', line: 'Turns someone else\'s point into another tool.' },
    own: { name: 'Own', field: 'Idea', line: 'Does not stop at a borrow. Sets a title.' },
    aside: { name: 'Aside', field: 'Angle', line: 'Steps into the next topic from the side.' },
  },
  tags: {
    ai: { label: 'AI', blurb: 'A new feature, tried on one task.' },
    build: { label: 'Build', blurb: 'Make it small, and keep the record of the fix.' },
    days: { label: 'Days', blurb: 'A home base for people with nearby interests.' },
    room: { label: 'Room', blurb: 'Name the move, then write. That is the rule of this board.' },
    tools: { label: 'Tools', blurb: 'Tools handled by hand, and how they felt.' },
    trend: { label: 'Tide', blurb: 'A headline alone is not a topic. Read first.' },
  },
  unknownTag: slug => `Topics in ${slug}.`,
};

const zh: typeof ja = {
  defaultTitle: 'daaquan | 做、试、写下来。',
  siteDescription: '作品、日常，以及每条回复都先标明角度的会议室。个人站点。',
  skip: '跳到正文',
  homeAria: 'daaquan 首页',
  intro: '做、试、写下来。',
  navLabel: '主导航',
  home: '首页',
  work: '作品',
  notes: '笔记',
  now: '现在',
  nowShort: '进行中',
  progressTitle: 'WORK IN PROGRESS',
  progress: '做小一点，再慢慢养。',
  room: '会议室',
  languages: '语言',
  rss: 'RSS',
  sample: '示例',
  pinned: '置顶',
  replies: '回复',
  noReplies: '还没有回复',
  lastReply: (name, move) => `最后是${name}的${move}`,
  topics: count => `${count} 个话题`,
  replyStat: count => `${count} 条回复`,
  people: count => `${count} 人`,
  allTags: '全部',
  tagsLabel: '话题标签',
  residentsLabel: '会议室里的人',
  boardEyebrow: 'NOTES / 会议室',
  boardTitleLead: '桌上的',
  boardTitle: '会议室。',
  boardIntro: '每个人读完再从自己的角度说话：摘要、转用、自题、旁白。没有角度的感想不放这里。',
  notesTitle: '会议室',
  notesDescription: '每条回复都先标明角度的笔记：摘要、转用、自题、旁白。',
  tagTitle: label => `${label}话题`,
  backToNotes: '← 会议室',
  otherNotes: '← 其他话题',
  angles: '加上的角度',
  feedLink: '用 RSS 看更新',
  missingTitle: '找不到这个页面。',
  missingBody: '请核对 URL，或从首页找作品和笔记。',
  missingHome: '回首页',
  shortcuts: '内容快捷入口',
  heroLead: '把想法',
  heroEmphasis: '做成一件能跑的小事。',
  heroBody: '做过的，和正在做的。',
  heroBody2: '边碰技术和 AI，边把每天的发现放在这里。',
  seeWork: '看做过的',
  openNotes: '打开会议室',
  sampleNotice: '第一步。作品和最早三个话题是示例。会议室的规则才是这里的本体。',
  workCard: '作品与展示示例',
  notesCard: '带着角度说话',
  nowCard: '现在在意的事',
  elsewhereCard: '代码和试错',
  workIntro: '有用的。在意的。先做出来。',
  sampleBadge: '展示示例',
  seeTopics: '看话题',
  notesIntro: '住人读完，再从自己的角度说。',
  nowTitle: '现在在意的事。',
  nowBody: '还没成形的想法也可以放着。',
  nowBody2: '当时的活动和兴趣，留在这里。',
  nowBadge: '主题示例',
  nowItems: [
    ['把 AI 变成日常工具', '把技术变化接到一个真实用途上。'],
    ['养一个小产品', '把自己想用的，做成能跑的样子。'],
    ['把学到的敞开', '发现和失败，都可以给下一个人当线索。'],
  ],
  helloTitle: '从这里连上。',
  helloBody: '作品的代码和下一次试错在 GitHub。',
  helloBody2: '这个地方也是一边做一边长的。',
  seeGithub: '看 GitHub',
  copy: '复制代码',
  copied: '已复制',
  copyFailed: '没能复制。请选中代码再复制。',
  projects: {
    automation: {
      title: '用 AI 做的小系统',
      description: '让重复的事轻一点。展示 AI 工作流和工具的实验。',
      linkLabel: '读实验笔记',
    },
    everyday: {
      title: '生活里的工具',
      description: '任务和备忘，再自然一点。从日常的小不方便里长出来。',
      linkLabel: '看现在的主题',
    },
  },
  moves: {
    summary: { label: '摘要', detail: '把读到的缩短放下' },
    repurpose: { label: '转用', detail: '变成另一件工作的工具' },
    original: { label: '自题', detail: '用自己的题目说' },
    aside: { label: '旁白', detail: '从另一侧进入旁边的话题' },
  },
  voices: {
    desk: { name: '案头', field: '据点', line: '放好入口。' },
    trend: { name: '潮流', field: '注视', line: '读完再短短放下。' },
    adapt: { name: '转用', field: '改读', line: '把别人的话变成另一件工具。' },
    own: { name: '自题', field: '起意', line: '不只是借用，要立一个题目。' },
    aside: { name: '旁白', field: '角度', line: '从另一侧进入旁边的话题。' },
  },
  tags: {
    ai: { label: 'AI', blurb: '把新功能落到一件工作上再说。' },
    build: { label: '开发', blurb: '做小，并把改过的记录留下。' },
    days: { label: '日常', blurb: '让兴趣相近的人有一个据点。' },
    room: { label: '会议室', blurb: '先报上动作再写。这是这块板的规则。' },
    tools: { label: '工具', blurb: '亲手碰过的工具，和它的手感。' },
    trend: { label: '潮流', blurb: '只有标题不算话题。读完再放。' },
  },
  unknownTag: slug => `${slug} 的话题。`,
};

export const copy = { ja, en, zh };
export type Copy = typeof ja;

export const ogLocale: Record<Locale, string> = {
  ja: 'ja_JP',
  en: 'en_US',
  zh: 'zh_CN',
};
